# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kirt08_contracts/auth/auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kirt08_contracts/auth/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n kirt08_contracts/auth/auth.proto\x12\x07\x61uth.v1\"2\n\x0eSendOtpRequest\x12\x12\n\nidentifier\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"\x1d\n\x0fSendOtpResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"B\n\x10VerifyOtpRequest\x12\x12\n\nidentifier\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\"@\n\x11VerifyOtpResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\"\'\n\x0eRefreshRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\">\n\x0fRefreshResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t2\xcd\x01\n\x0b\x41uthService\x12<\n\x07SendOtp\x12\x17.auth.v1.SendOtpRequest\x1a\x18.auth.v1.SendOtpResponse\x12\x42\n\tVerifyOtp\x12\x19.auth.v1.VerifyOtpRequest\x1a\x1a.auth.v1.VerifyOtpResponse\x12<\n\x07Refresh\x12\x17.auth.v1.RefreshRequest\x1a\x18.auth.v1.RefreshResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kirt08_contracts.auth.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDOTPREQUEST']._serialized_start=45
  _globals['_SENDOTPREQUEST']._serialized_end=95
  _globals['_SENDOTPRESPONSE']._serialized_start=97
  _globals['_SENDOTPRESPONSE']._serialized_end=126
  _globals['_VERIFYOTPREQUEST']._serialized_start=128
  _globals['_VERIFYOTPREQUEST']._serialized_end=194
  _globals['_VERIFYOTPRESPONSE']._serialized_start=196
  _globals['_VERIFYOTPRESPONSE']._serialized_end=260
  _globals['_REFRESHREQUEST']._serialized_start=262
  _globals['_REFRESHREQUEST']._serialized_end=301
  _globals['_REFRESHRESPONSE']._serialized_start=303
  _globals['_REFRESHRESPONSE']._serialized_end=365
  _globals['_AUTHSERVICE']._serialized_start=368
  _globals['_AUTHSERVICE']._serialized_end=573
# @@protoc_insertion_point(module_scope)
