# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kirt08_contracts/account/account.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kirt08_contracts/account/account.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&kirt08_contracts/account/account.proto\x12\naccount.v1\"\x1f\n\x11GetAccountRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"\x94\x01\n\x12GetAccountResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05phone\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x19\n\x11is_phone_verified\x18\x04 \x01(\x08\x12\x19\n\x11is_email_verified\x18\x05 \x01(\x08\x12\x1e\n\x04role\x18\x06 \x01(\x0e\x32\x10.account.v1.Role*\x1b\n\x04Role\x12\x08\n\x04USER\x10\x00\x12\t\n\x05\x41\x44MIN\x10\x01\x32]\n\x0e\x41\x63\x63ountService\x12K\n\nGetAccount\x12\x1d.account.v1.GetAccountRequest\x1a\x1e.account.v1.GetAccountResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kirt08_contracts.account.account_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROLE']._serialized_start=238
  _globals['_ROLE']._serialized_end=265
  _globals['_GETACCOUNTREQUEST']._serialized_start=54
  _globals['_GETACCOUNTREQUEST']._serialized_end=85
  _globals['_GETACCOUNTRESPONSE']._serialized_start=88
  _globals['_GETACCOUNTRESPONSE']._serialized_end=236
  _globals['_ACCOUNTSERVICE']._serialized_start=267
  _globals['_ACCOUNTSERVICE']._serialized_end=360
# @@protoc_insertion_point(module_scope)
